### ISSUE TITLE
RC101

### ISSUE THREAD

**Issue by tomjhandley** [FlukeAndFeather/maxspeed#1]
1) What version of the prerequisites do you have? (This should include RStudio, R, tidyverse, devtools, and rrtools.)

RStudio: 2021.09.1+372 "Ghost Orchid" Release (8b9ced188245155642d024aa3630363df611088a, 2021-11-08) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

R: R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"

Packages: tidyverse, devtools, and rrtools loaded

2) In your words, how would you briefly describe a research compendium?

A guide to how a data analysis was completed, both through code but also through a description of how that code was applied to the data.

A research compendium accompanies, enhances, or is a scientific publication providing data, code, and documentation for reproducing a scientific workflow. 

Something that:
- Organises files
- Maintains separation of data method and output
- Describes relationship between those three

3) Consider a paper you contributed to (whether you were on the author list or not). Were the data and code published with the paper? If so, how? Say another scientist wants to reproduce your results. What challenges do you think they would run into?
- Relevant to this is a research project I am currently working on. I am trying to recreate the methods from a previous data analysis, transposed into a new data set. The original analysis does not provide any kind of code with the original paper, and as a result I have tried to recreate their study and methodology from the methods section. I have access to their original dataset but have still  struggled to replicate their results with the description for their own code. A research compendium would have been invaluably useful.

**Comment by FlukeAndFeather** [comment]
> I have access to their original dataset but have still struggled to replicate their results with the description for their own code.

This is super common! I've run into the same issue. Applying a model to new data **should** be easy but rarely is. If you want a second set of eyes on any of it please let me know.
