### ISSUE TITLE
RC101

### ISSUE THREAD

**Issue by kathyle9** [FlukeAndFeather/maxspeed#45]
1. I have Version 1.4.1106 of RStudio and R version 4.0.4. I have tidyverse version 1.3.1 and devtools version 2.4.3. My version of rrtools is 0.1.5.
2. A research compendium is a framework for interacting with data in a way that is clearly communicated, outlined, and reproducible. This is achieved by relying on conventions prevalent in the field, separating data from the analysis, and specifying the tools and environment that was used.
3. In this paper that my undergraduate lab published (https://doi-org.stanford.idm.oclc.org/10.1038/s41467-021-20897-y), the RNA sequencing data was available through the NCBI Gene Expression Omnibus. All the code is on Zenodo, and the packages and environments are in Supplementary Dataset 6. One challenge someone might run into is that only the main packages and software are listed in the supplement. Someone might have trouble replicating the exact environment due to missing dependencies that are not listed. A docker container or some other way to document whole environments might be better for reproducibility.

**Comment by elhazen** [comment]
This is a really cool paper. Have you (or has anyone that you know) tried replicating the analysis from the paper? It could be a final project for the class!

**Comment by kathyle9** [comment]
No, I have not tried replicating this analysis, but yes I would love to!
